{% set version = "0.11.3.post1" %}

package:
  name: pyrepl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyrepl/pyrepl-{{ version }}.tar.gz
  sha256: 0ca7568c8be919b69f99644d29d31738a5b1a87750d06dd36564bcfad278d402

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools  # [py>=313]
  run:
    - python
    - ncurses

test:
  imports:
    - pyrepl

about:
  home: https://pypi.org/project/pyrepl/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A library for building flexible command line interfaces'

  description: |
    pyrepl is a Python library, inspired by readline, for building flexible
    command line interfaces, featuring:

     * sane multi-line editing
     * history, with incremental search
     * completion, including displaying of available options
     * a fairly large subset of the readline emacs-mode keybindings
     * a liberal, Python-style, license
     * a new python top-level.
  doc_url: https://pypi.org/project/pyrepl/
  dev_url: https://github.com/bretello/pyrepl

extra:
  recipe-maintainers:
    - anjos
    - kynan
