{% set version = "0.11.4" %}

package:
  name: pyrepl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyrepl/pyrepl-{{ version }}.tar.gz
  sha256: efe988b4a6e5eed587e9769dc2269aeec2b6feec2f5d77995ee85b9ad7cf7063
  patches:
    - find-libcurses-elf-binary.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - ncurses

test:
  source_files:
    - tests
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-timeout
    - pexpect
    - pip
  commands:
    - pip check
    - TERM=xterm-256color pytest -sv -ra --ignore tests/test_curses.py --timeout=10 tests
  imports:
    - pyrepl

about:
  home: https://pypi.org/project/pyrepl/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A library for building flexible command line interfaces'

  description: |
    pyrepl is a Python library, inspired by readline, for building flexible
    command line interfaces, featuring:

     * sane multi-line editing
     * history, with incremental search
     * completion, including displaying of available options
     * a fairly large subset of the readline emacs-mode keybindings
     * a liberal, Python-style, license
     * a new python top-level.
  doc_url: https://pypi.org/project/pyrepl/
  dev_url: https://github.com/bretello/pyrepl

extra:
  recipe-maintainers:
    - anjos
    - kynan
